In [1]:
import torch
import numpy as np

# PyTorch GPU check

In [2]:
torch.__version__

'1.2.0+cu92'

In [3]:
torch.cuda.is_available()

True

In [4]:
torch.cuda.current_device()

0

In [5]:
torch.cuda.device(0)

In [6]:
torch.cuda.device_count()

1

In [7]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce GT 730'

# Convert to tensor 

In [8]:
arr = np.array([1,2,3,4,5])

In [9]:
x = torch.as_tensor(arr)

In [10]:
print(x)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)


In [11]:
arr1 = np.arange(0,12,1)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
arr2d = arr1.reshape(4,3)
arr2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
torch.as_tensor(arr2d)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]], dtype=torch.int32)

In [14]:
torch.tensor(arr2d)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]], dtype=torch.int32)

In [15]:
torch.from_numpy(arr2d)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]], dtype=torch.int32)

# tensor vs. Tensor 

## tensor [ int ]

In [16]:
arr2 = [1,2,3,4,5]
torch.tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

## Tensor [ float ]

In [19]:
torch.Tensor(arr)

tensor([1., 2., 3., 4., 5.])